### ISSUE TITLE
Internal GraalVM error when running

### ISSUE THREAD

**Issue by tpluscode** [restcli/restcli#100]
I downloaded the latest `jar` from releases (v2.0.1).
I run my test with:

> java -jar  restcli.jar -d test -e dev test/queries/*.http

The result is this:

```
┌────────────────────┐
│restcli             │
├────────────────┬───┤
│Environment name│dev│
└────────────────┴───┘
[To redirect Truffle log output to a file use one of the following options:
* '--log.file=<path>' if the option is passed using a guest language launcher.
* '-Dpolyglot.log.file=<path>' if the option is passed using the host Java launcher.
* Configure logging using the polyglot embedding API.]
[engine] WARNING: The polyglot context is using an implementation that does not support runtime compilation.
The guest application code will therefore be executed in interpreted mode only.
Execution only in interpreted mode will strongly impact the guest application performance.
For more information on using GraalVM see https://www.graalvm.org/java/quickstart/.
To disable this warning the '--engine.WarnInterpreterOnly=false' option or use the '-Dpolyglot.engine.WarnInterpreterOnly=false' system property.
org.graalvm.polyglot.PolyglotException: java.lang.IllegalStateException: No language for id regex found. Supported languages are: [js]
    at com.oracle.truffle.polyglot.PolyglotEngineException.illegalState(PolyglotEngineException.java:129)
    at com.oracle.truffle.polyglot.PolyglotEngineImpl.findLanguage(PolyglotEngineImpl.java:722)
    at com.oracle.truffle.polyglot.EngineAccessor$EngineImpl.parseForLanguage(EngineAccessor.java:244)
    at com.oracle.truffle.api.TruffleLanguage$Env.parseInternal(TruffleLanguage.java:2486)
    at com.oracle.truffle.js.runtime.builtins.JSRegExp.es5GetEmptyRegexEarly(JSRegExp.java:358)
    at com.oracle.truffle.js.runtime.builtins.JSRegExp.createPrototype(JSRegExp.java:325)
    at com.oracle.truffle.js.runtime.builtins.JSConstructorFactory$Default.createConstructorAndPrototype(JSConstructorFactory.java:68)
    at com.oracle.truffle.js.runtime.builtins.JSRegExp.createConstructor(JSRegExp.java:377)
    at com.oracle.truffle.js.runtime.JSRealm.<init>(JSRealm.java:511)
    at com.oracle.truffle.js.runtime.JSContext.createRealm(JSContext.java:664)
    at com.oracle.truffle.js.lang.JavaScriptLanguage.createContext(JavaScriptLanguage.java:307)
    at com.oracle.truffle.js.lang.JavaScriptLanguage.createContext(JavaScriptLanguage.java:115)
    at com.oracle.truffle.api.LanguageAccessor$LanguageImpl.createEnvContext(LanguageAccessor.java:282)
    at com.oracle.truffle.polyglot.PolyglotLanguageContext.ensureCreated(PolyglotLanguageContext.java:541)
    at com.oracle.truffle.polyglot.PolyglotLanguageContext.ensureCreated(PolyglotLanguageContext.java:485)
    at com.oracle.truffle.polyglot.PolyglotLanguageContext.ensureInitialized(PolyglotLanguageContext.java:627)
    at com.oracle.truffle.polyglot.PolyglotContextImpl.eval(PolyglotContextImpl.java:1346)
    at com.oracle.truffle.polyglot.PolyglotContextDispatch.eval(PolyglotContextDispatch.java:62)
    at org.graalvm.polyglot.Context.eval(Context.java:375)
    at com.oracle.truffle.js.scriptengine.GraalJSScriptEngine.evalInternal(GraalJSScriptEngine.java:376)
    at com.oracle.truffle.js.scriptengine.GraalJSBindings.initGlobal(GraalJSBindings.java:94)
    at com.oracle.truffle.js.scriptengine.GraalJSBindings.initContext(GraalJSBindings.java:90)
    at com.oracle.truffle.js.scriptengine.GraalJSBindings.requireContext(GraalJSBindings.java:84)
    at com.oracle.truffle.js.scriptengine.GraalJSBindings.entrySet(GraalJSBindings.java:170)
    at java.base/java.util.AbstractMap.containsKey(AbstractMap.java:144)
    at java.scripting/javax.script.SimpleScriptContext.getAttribute(SimpleScriptContext.java:158)
    at com.oracle.truffle.js.scriptengine.GraalJSScriptEngine.createSource(GraalJSScriptEngine.java:430)
    at com.oracle.truffle.js.scriptengine.GraalJSScriptEngine.eval(GraalJSScriptEngine.java:400)
    at java.scripting/javax.script.AbstractScriptEngine.eval(AbstractScriptEngine.java:249)
    at uos.dev.restcli.jsbridge.JsClient.<init>(JsClient.kt:22)
    at uos.dev.restcli.jsbridge.JsClient.<init>(JsClient.kt:15)
    at uos.dev.restcli.jsbridge.JsClient.<init>(JsClient.kt:16)
    at uos.dev.restcli.HttpRequestFilesExecutor.<init>(HttpRequestFilesExecutor.kt:31)
    at uos.dev.restcli.RestCli.call(RestCli.kt:73)
    at uos.dev.restcli.RestCli.call(RestCli.kt:12)
    at picocli.CommandLine.executeUserObject(CommandLine.java:1953)
    at picocli.CommandLine.access$1300(CommandLine.java:145)
    at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2358)
    at picocli.CommandLine$RunLast.handle(CommandLine.java:2352)
    at picocli.CommandLine$RunLast.handle(CommandLine.java:2314)
    at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
    at picocli.CommandLine$RunLast.execute(CommandLine.java:2316)
    at picocli.CommandLine.execute(CommandLine.java:2078)
    at uos.dev.restcli.AppKt.main(App.kt:9)
Caused by: Attached Guest Language Frames (0)
Internal GraalVM error, please report at https://github.com/oracle/graal/issues/.
```

I run macOS Catalina. Here's the output of `java --version`:

```
java 16.0.2 2021-07-20
Java(TM) SE Runtime Environment (build 16.0.2+7-67)
Java HotSpot(TM) 64-Bit Server VM (build 16.0.2+7-67, mixed mode, sharing)
```

The tests works fine when running with Java8 using the latest version from `brew` (v1.7.4)

**Comment by quangson91** [comment]
@tpluscode 
I have a question.
Does version `v1.7.4` work with java 16:
```
java 16.0.2 2021-07-20
Java(TM) SE Runtime Environment (build 16.0.2+7-67)
Java HotSpot(TM) 64-Bit Server VM (build 16.0.2+7-67, mixed mode, sharing)
```

**Comment by tpluscode** [comment]
No, with java 16 I was getting the nashorn error

> java.lang.IllegalStateException: ScriptEngineManager().getEngineByName("nashorn") must not be null
