### ISSUE TITLE
getEngineByName("nashorn") must not be null

### ISSUE THREAD

**Issue by lester-s** [restcli/restcli#56]
Hello,

I have been trying to dockerize your CLI tool.
Here is the dockerfile content:
`FROM openjdk:latest
WORKDIR Home
COPY restcli.jar .
COPY Usecases ./Usecases`

I push the version 1.7.3 of the CLI tool into it.

i run this command to execute tests:

`java -jar ../restcli.jar -e "dev" Testusecase.http`

Here is the stack trace of the error:

`java.lang.IllegalStateException: ScriptEngineManager().getEngineByName("nashorn") must not be null
        at uos.dev.restcli.jsbridge.JsClient.<init>(JsClient.kt:18)
        at uos.dev.restcli.HttpRequestFilesExecutor.<init>(HttpRequestFilesExecutor.kt:24)
        at uos.dev.restcli.RestCli.call(RestCli.kt:59)
        at uos.dev.restcli.RestCli.call(RestCli.kt:16)
        at picocli.CommandLine.executeUserObject(CommandLine.java:1853)
        at picocli.CommandLine.access$1100(CommandLine.java:145)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2255)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2249)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2213)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2080)
        at picocli.CommandLine.execute(CommandLine.java:1978)
        at uos.dev.restcli.AppKt.main(App.kt:9)`

running java -version ouput: 
`java -version
openjdk version "15.0.1" 2020-10-20
OpenJDK Runtime Environment (build 15.0.1+9-18)
OpenJDK 64-Bit Server VM (build 15.0.1+9-18, mixed mode, sharing)`

Any idea how to fix this ?

**Comment by lester-s** [comment]
Seems like i found the problem. Version 15 of Java is too high. needs version 8. i tried using this docker image for JRE base image. 
`mcr.microsoft.com/java/jre:8-zulu-alpine`
It's now running fine.
